apiVersion: v1
kind: Secret
metadata:
  name: mongo-atlas-credentials
  labels:
    app.kubernetes.io/part-of: mongo-tweets-app
data:
  MONGO_ATLAS_URI: mongodb+srv://IRGC:iraniraniran@iranmaldb.gurutam.mongodb.net/
type: Opaque
